# Generated by Django 6.0.6 on 2026-06-07 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('language_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{3}$', 'Must be exactly 3 alphabetic characters.')])),
                ('usage', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='buildingblock',
            name='sentences',
            field=models.ManyToManyField(blank=True, related_name='building_blocks', to='core.sentence'),
        ),
    ]
