# Generated by Django 6.0.6 on 2026-06-08 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sentence_buildingblock_sentences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeechAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('sentences', models.ManyToManyField(blank=True, related_name='speech_acts', to='core.sentence')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_acts', to='core.situation')),
            ],
        ),
    ]
