# Generated by Django 6.0.6 on 2026-06-08 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_situation_speechact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speechact',
            name='sentences',
        ),
        migrations.RemoveField(
            model_name='speechact',
            name='situation',
        ),
        migrations.CreateModel(
            name='SituationalUtterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='core.sentence')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='core.situation')),
                ('speech_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='core.speechact')),
            ],
        ),
    ]
