# Generated by Django 6.0.6 on 2026-06-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_speechact_sentences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='usage',
        ),
    ]
