# Generated by Django 6.0.6 on 2026-06-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_sentence_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situationalutterance',
            name='context',
            field=models.TextField(blank=True),
        ),
    ]
