# Generated by Django 6.0.6 on 2026-06-09 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_language_and_fks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('speakers', models.JSONField(default=list)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='core.situation')),
            ],
        ),
        migrations.CreateModel(
            name='DialogNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.TextField()),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.dialog')),
            ],
        ),
        migrations.AddField(
            model_name='dialog',
            name='start_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.dialognode'),
        ),
        migrations.CreateModel(
            name='DialogUtterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_utterances', to='core.dialognode')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='core.dialognode')),
                ('speech_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_utterances', to='core.speechact')),
            ],
        ),
        migrations.CreateModel(
            name='DialogLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_lines', to='core.sentence')),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.dialogutterance')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
