[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.1",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.14.0",
    "djangorestframework>=3.18.0",
    "djangorestframework-simplejwt>=5.5.1",
    "gunicorn>=26.0.0",
    "openai>=1.50.0",
    "psycopg[binary]>=3.3.4",
    "pycountry>=26.2.16",
    "whitenoise>=6.12.0",
]
