# Generated by Django 6.1 on 2026-08-08 12:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import learning.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=3, validators=[learning.models.validators.validate_iso639_3])),
                ('description', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('VOCAB', 'Vocabulary'), ('SENTENCE', 'Sentence')], max_length=16)),
                ('language', models.CharField(max_length=3, validators=[learning.models.validators.validate_iso639_3])),
                ('content', models.TextField()),
                ('credit', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('TRUSTED', 'Trusted'), ('NEEDS_CHECKING', 'Needs checking')], default='NEEDS_CHECKING', max_length=16)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'language', 'content'), name='unique_node_kind_language_content')],
            },
        ),
        migrations.CreateModel(
            name='Rel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('EXAMPLE', 'Example'), ('PART_OF', 'Part of'), ('TRANSLATION', 'Translation')], max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('credit', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('TRUSTED', 'Trusted'), ('NEEDS_CHECKING', 'Needs checking')], default='NEEDS_CHECKING', max_length=16)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rels', to='learning.node')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rels', to='learning.node')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sender', 'receiver', 'label'), name='unique_rel_sender_receiver_label')],
            },
        ),
        migrations.CreateModel(
            name='SituationRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_relations', to='learning.node')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_relations', to='learning.situation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('situation', 'node'), name='unique_situation_relation')],
            },
        ),
    ]
