# Generated by Django 6.1 on 2026-08-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='state',
            field=models.CharField(choices=[('TRUSTED', 'Trusted'), ('NEEDS_CHECKING', 'Needs checking'), ('AUTO_GENERATED', 'Auto-generated')], default='NEEDS_CHECKING', max_length=16),
        ),
        migrations.AlterField(
            model_name='rel',
            name='state',
            field=models.CharField(choices=[('TRUSTED', 'Trusted'), ('NEEDS_CHECKING', 'Needs checking'), ('AUTO_GENERATED', 'Auto-generated')], default='NEEDS_CHECKING', max_length=16),
        ),
    ]
